# Generated by Django 4.2.4 on 2023-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("artist_name", models.CharField(max_length=128)),
                ("album_name", models.CharField(max_length=128)),
                ("song_name", models.CharField(max_length=128)),
                ("user", models.CharField(max_length=32)),
                ("ranking", models.IntegerField()),
            ],
        ),
    ]
