# Generated by Django 4.2.4 on 2023-09-25 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bracketify", "0002_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="Players",
        ),
    ]
